version: "3"

services:
  api:
    build: .
    entrypoint: python
    command: index.py
    working_dir: /api
    volumes:
      - ./api:/api
      - ./data:/data
    ports:
      - 8000:8000
    restart: on-failure
